#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#1d1f21"
bspc config active_border_color "#a54242"
bspc config focused_border_color "#de935f"
bspc config presel_feedback_color "#8c9440"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on

nitrogen --restore &
picom &
~/.config/polybar/launch.sh &
#dunst &
pulseaudio &
emacs --daemon &
